export default [
  {
    componentLabel: "Hero",
    componentName: "builder-hero",
    attributes: {
      title: "This is a title for your hero scene",
      subtitle: "This is a subtitle for your hero scene",
      textColor: "white",
      buttonColor: "#b57e6b",
      alignment: { alignItems: "center", justifyContent: "center" },
      resizable: false,
    },
    children: [],
    id: "991bef31-156c-49f7-b6a8-e5b3c559673a",
  },
  {
    componentLabel: "Partners",
    componentName: "builder-partners",
    attributes: { itemCount: "5", height: "200", resizable: true },
    children: [],
    id: "a9cb7051-f6a7-4a0c-a471-5b37af88f227",
  },
  {
    componentName: "builder-text-block",
    componentLabel: "TextBlock",
    attributes: {
      title: "A catchphrase for your section",
      description: "A little text description",
      textColor: "black",
      bgColor: "white",
      alignment: { alignItems: "center", justifyContent: "center" },
      height: "300",
      resizable: true,
    },
    children: [],
    id: "2480f9eb-eae0-43d0-bf52-a555fdcc4e29",
  },
  {
    componentLabel: "Gallery",
    componentName: "builder-gallery",
    attributes: {
      columns: "3",
      itemCount: "9",
      hasColGap: true,
      colGap: "5",
      hasSectionGap: true,
      resizable: false,
    },
    children: [],
    id: "bb65494c-7e7f-4c1d-9715-2ff0d4f8ced1",
  },
  {
    componentLabel: "Section",
    componentName: "builder-section",
    attributes: {
      title: "A catchphrase for your section",
      description: "A little text description",
      textColor: "black",
      bgColor: "white",
      alignment: { alignItems: "center", justifyContent: "center" },
      resizable: false,
      reversed: false,
      hasSectionGap: false,
    },
    children: [],
    id: "ee2b577e-fd9f-4f21-a2d4-21a7bbac68e2",
  },
];
